### PR TITLE
update rpiboot bootcode.bin to 2023-01-11 release

### PR DESCRIPTION
**Pull request by WeeJeWel**
This enables flashing the CM4 Rev. 1.1.

### CODE REVIEW

**Comment by mcraa** [comment]
hi, #44 updated the bootcode.bin, and we just updated the start4.elf in #48 
is [v1.0.6](https://github.com/balena-io-modules/node-raspberrypi-usbboot/releases/tag/v1.0.6) work for you ?

**Comment by WeeJeWel** [comment]
Can I test with a version of Balena Etcher app?

**Comment by mcraa** [comment]
the PR was created already for Etcher https://github.com/balena-io/etcher/pull/3980
You can check it soon.

**Comment by mcraa** [comment]
@WeeJeWel this release has it 
https://github.com/balena-io/etcher/releases/tag/v1.14.2

**Pull request closed without merging**
